// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payroll.Data;

namespace Payroll.Data.Migrations
{
    [DbContext(typeof(PayrollContext))]
    [Migration("20200212224114_RemoveExtraMinimumWageSeeds")]
    partial class RemoveExtraMinimumWageSeeds
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Payroll.Domain.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Payroll.Domain.CrewBossPayLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("Crew")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LayoffId")
                        .HasColumnType("int");

                    b.Property<string>("PayMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuickBaseRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CrewBossPayLines");
                });

            modelBuilder.Entity("Payroll.Domain.CrewBossWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkerCountThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CrewBossWages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(5307),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(5336),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 24.5m,
                            WorkerCountThreshold = 36
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(7936),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(7957),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 24m,
                            WorkerCountThreshold = 35
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8034),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8041),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 23.5m,
                            WorkerCountThreshold = 34
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8047),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8052),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 23m,
                            WorkerCountThreshold = 33
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8057),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8062),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 22.5m,
                            WorkerCountThreshold = 32
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8068),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8073),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 22m,
                            WorkerCountThreshold = 31
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8078),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8085),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 21.5m,
                            WorkerCountThreshold = 30
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8090),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8212),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 21m,
                            WorkerCountThreshold = 29
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8218),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8223),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 20.5m,
                            WorkerCountThreshold = 28
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8229),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8233),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 20m,
                            WorkerCountThreshold = 27
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8239),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8243),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 19.5m,
                            WorkerCountThreshold = 26
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8249),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8253),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 19m,
                            WorkerCountThreshold = 25
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8259),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8264),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 18.5m,
                            WorkerCountThreshold = 24
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8269),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8274),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 18.25m,
                            WorkerCountThreshold = 23
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8279),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8284),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 18m,
                            WorkerCountThreshold = 22
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8289),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8294),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 17.75m,
                            WorkerCountThreshold = 21
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8300),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8304),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 17.5m,
                            WorkerCountThreshold = 20
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8310),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8315),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 17.25m,
                            WorkerCountThreshold = 19
                        },
                        new
                        {
                            Id = 19,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8321),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8325),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 17m,
                            WorkerCountThreshold = 18
                        },
                        new
                        {
                            Id = 20,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8331),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8335),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 16.75m,
                            WorkerCountThreshold = 17
                        },
                        new
                        {
                            Id = 21,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8341),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8345),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 16.5m,
                            WorkerCountThreshold = 16
                        },
                        new
                        {
                            Id = 22,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8351),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8355),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 16.25m,
                            WorkerCountThreshold = 15
                        },
                        new
                        {
                            Id = 23,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8361),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 855, DateTimeKind.Local).AddTicks(8365),
                            EffectiveDate = new DateTime(2019, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 16m,
                            WorkerCountThreshold = 0
                        });
                });

            modelBuilder.Entity("Payroll.Domain.MinimumWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MinimumWages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 848, DateTimeKind.Local).AddTicks(5885),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 852, DateTimeKind.Local).AddTicks(9333),
                            EffectiveDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 8m
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2788),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2827),
                            EffectiveDate = new DateTime(2014, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 9m
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2877),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2882),
                            EffectiveDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 10m
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2963),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2970),
                            EffectiveDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 10.5m
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2976),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2980),
                            EffectiveDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 11m
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2987),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2991),
                            EffectiveDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 12m
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(2998),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(3003),
                            EffectiveDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 13m
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(3009),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(3014),
                            EffectiveDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 14m
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(3021),
                            DateModified = new DateTime(2020, 2, 12, 14, 41, 13, 853, DateTimeKind.Local).AddTicks(3026),
                            EffectiveDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 15m
                        });
                });

            modelBuilder.Entity("Payroll.Domain.RanchPayLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AlternativeWorkWeek")
                        .HasColumnType("bit");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("Crew")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FiveEight")
                        .HasColumnType("bit");

                    b.Property<decimal>("GrossFromHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossFromPieces")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LaborCode")
                        .HasColumnType("int");

                    b.Property<int>("LayoffId")
                        .HasColumnType("int");

                    b.Property<decimal>("OtDtWotHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtDtWotRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PieceRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pieces")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuickBaseRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RanchPayLines");
                });
#pragma warning restore 612, 618
        }
    }
}
