// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payroll.Data;

namespace Payroll.Data.Migrations
{
    [DbContext(typeof(PayrollContext))]
    [Migration("20200212221818_SeedMinimumWage")]
    partial class SeedMinimumWage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Payroll.Domain.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Payroll.Domain.CrewBossPayLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("Crew")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Gross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LayoffId")
                        .HasColumnType("int");

                    b.Property<string>("PayMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuickBaseRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CrewBossPayLines");
                });

            modelBuilder.Entity("Payroll.Domain.CrewBossWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("WorkerCountThreshold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CrewBossWages");
                });

            modelBuilder.Entity("Payroll.Domain.MinimumWage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Wage")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MinimumWages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 937, DateTimeKind.Local).AddTicks(6431),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(319),
                            EffectiveDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 8m
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2719),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2751),
                            EffectiveDate = new DateTime(2014, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 9m
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2800),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2806),
                            EffectiveDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 10m
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2906),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2923),
                            EffectiveDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 10.5m
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2930),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2932),
                            EffectiveDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 11m
                        },
                        new
                        {
                            Id = 6,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2935),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2938),
                            EffectiveDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 12m
                        },
                        new
                        {
                            Id = 7,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2941),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2944),
                            EffectiveDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 13m
                        },
                        new
                        {
                            Id = 8,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2947),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2949),
                            EffectiveDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 14m
                        },
                        new
                        {
                            Id = 9,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2953),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2955),
                            EffectiveDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 15m
                        },
                        new
                        {
                            Id = 10,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2959),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2961),
                            EffectiveDate = new DateTime(2010, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 8m
                        },
                        new
                        {
                            Id = 11,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2964),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2967),
                            EffectiveDate = new DateTime(2014, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 9m
                        },
                        new
                        {
                            Id = 12,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2970),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2973),
                            EffectiveDate = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 10m
                        },
                        new
                        {
                            Id = 13,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2976),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2979),
                            EffectiveDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 10.5m
                        },
                        new
                        {
                            Id = 14,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2982),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2984),
                            EffectiveDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 11m
                        },
                        new
                        {
                            Id = 15,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2988),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2990),
                            EffectiveDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 12m
                        },
                        new
                        {
                            Id = 16,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2993),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2996),
                            EffectiveDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 13m
                        },
                        new
                        {
                            Id = 17,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(2999),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(3002),
                            EffectiveDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 14m
                        },
                        new
                        {
                            Id = 18,
                            DateCreated = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(3005),
                            DateModified = new DateTime(2020, 2, 12, 14, 18, 17, 941, DateTimeKind.Local).AddTicks(3007),
                            EffectiveDate = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Wage = 15m
                        });
                });

            modelBuilder.Entity("Payroll.Domain.RanchPayLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AlternativeWorkWeek")
                        .HasColumnType("bit");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.Property<int>("Crew")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FiveEight")
                        .HasColumnType("bit");

                    b.Property<decimal>("GrossFromHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossFromPieces")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LaborCode")
                        .HasColumnType("int");

                    b.Property<int>("LayoffId")
                        .HasColumnType("int");

                    b.Property<decimal>("OtDtWotHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtDtWotRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherGross")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PieceRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Pieces")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuickBaseRecordId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WeekEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RanchPayLines");
                });
#pragma warning restore 612, 618
        }
    }
}
